### ISSUE TITLE
Fonts without UTF8 characters do not compile

### ISSUE THREAD

**Issue by SomeRanDev** [laqieer/gba-free-fonts#4]
Whenever I use a font without utf8 characters, the assert at [`include/bn_sprite_font.h:119`](https://github.com/GValiente/butano/blob/6ff67515699cbe3dff4721766c1ceed0025dd09a/butano/include/bn_sprite_font.h#L119C10-L119C10) fails at compile-time. It fixes itself if I add just a single utf8 character, so not a huge deal... but the assert message is very confusing, and it took me a bit to figure out what was happening, so figured I'd report. 

To replicate, I've attached the font I'm using. Just drop in example project and the error will occur:
[madou_futo_maru_gothic.zip](https://github.com/laqieer/gba-free-fonts/files/12286925/madou_futo_maru_gothic.zip)

---

_Attaching error message to help anyone with similar error search for this_
```
in 'constexpr' expansion of '((bn::sprite_font*)this)->bn::sprite_font::sprite_font((* & item), (* & utf8_characters_ref), (* & character_widths_ref), 0)'
butano/include/bn_assert.h:133:25: error: call to non-'constexpr' function 'void __assert_func(const char*, int, const char*, const char*)'
  133 |                         assert(condition); \
      |                         ^~~~~~
butano/include/bn_sprite_font.h:119:9: note: in expansion of macro 'BN_ASSERT'
  119 |         BN_ASSERT(character_widths_ref.empty() ||
devkitARM/arm-none-eabi/include/assert.h:41:6: note: 'void __assert_func(const char*, int, const char*, const char*)' declared here
   41 | void __assert_func (const char *, int, const char *, const char *)
      |      ^~~~~~~~~~~~~
make[2]: *** [/devkitARM/base_rules:39: FontLoader.o] Error 1
make[1]: *** [/butano/butano.mak:207: build] Error 2
make: *** [/butano/butano.mak:202: all] Error 2
  ```

**Comment by 6TELOIV** [comment]
Getting the same error here.

**Comment by laqieer** [comment]
BMFont is for variable width characters, but utf8 characters map is required to construct font with variable width in butano, and [utf8 characters map cannot be empty](https://github.com/GValiente/butano/blob/591a45bb42ef164c60858e34be8ab7a2a9da7486/butano/include/bn_utf8_characters_map.h#L78):
```
    static_assert(! Utf8Characters.empty());
```
Therefore, it is required to include at least 1 utf8 character in the font and text as a workaround.
@GValiente not a big deal but feel free to comment if any, thanks!

**Comment by GValiente** [comment]
Hi :)

Could you try if it works now? 
https://github.com/GValiente/butano/commit/cd41117f59873d9ce1afb54c42f098df2d639aba

**Comment by laqieer** [comment]
> Hi :)
> 
> Could you try if it works now? [GValiente/butano@cd41117](https://github.com/GValiente/butano/commit/cd41117f59873d9ce1afb54c42f098df2d639aba)

It works now. Thanks!
